# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8f4256e213115f0f481238bcc67e48c8f0bfa7f609b7cad01c72d9fbd949a6b2d18c601c93513be8188b125e1d6ab9242f13353b8f9b01210c55388b894241c5

test:
  secret_key_base: edfd1f5609adc51ad3f8700d87a2972b147f3aab9dd9757f89d7a2ce5361df7a89de09392ebe24c763f967225b58b43dc991bb0e2fe5922db4584f94786bccea

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
